# Workflow to run tests using the latest pipenv environment

name: Run tests

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
          python --version; pip --version; pipenv --version

      - name: Install dependencies from the pipfile.lock
        run: |
          pipenv sync --dev

      - name: Run all tests
        run: |
          pipenv run pytest --cov=src

